### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by andrewresearch** [emorynlp/nlp4j#28]
Hi, 
is NLP4J an active project? 
I read on the discussion forum that the team is currently porting the project to Python.
Does that mean that the java version is likely to be abandoned?
Andrew

**Comment by jdchoi77** [comment]
Andrew,

As you heard, currently our team is focusing on the python version of this tool using deep learning.  We are going to release the first version sometime in the Fall, and we probably will come back to NLP4J after the release although there is a chance that the Java version is not going to be updated as much.  Deep learning is single-handedly killing Java for the machine learning community :(

Jinho

**Comment by andrewresearch** [comment]
OK Thanks.
